[package]
name = "gtk4_col_view"
version = "0.1.0"
authors = ["Nico Just <mail@njust.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = {git = "https://github.com/gtk-rs/gtk4-rs.git"}
once_cell = "1.7.2"